import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:http/http.dart' as http;
import 'package:kader_app/api/api_settings.dart';
import 'package:kader_app/models/autogenerated.dart';
import 'package:kader_app/models/result.dart';

class ApiController{
    Future <List<Result>> indexPost() async{
      var response = await http.get(Uri.parse(ApiSettings.API_POST));
      if(response != null && response.statusCode == 200) {
        if (response.body != null) {
          var autongenerater = Autogenerated.fromJson(
              jsonDecode(response.body));
          return autongenerater.result;
        }
      }
          return [];
    }

//      // print(response.body);
//       jsonDecode(response.body);
//       for (var result in autongenerater.result){
//         print("post-title ${result.postTitle} ${result.imageUrl}");
//       }
 }