import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:http/http.dart' as http;
import 'package:kader_app/api/api_settings.dart';
import 'package:kader_app/models/autogenerated.dart';
import 'package:kader_app/models/base_generic_object_response.dart';
import 'package:kader_app/models/result.dart';
import 'package:kader_app/models/user.dart';
import 'package:kader_app/prefs/user_perferences.dart';

class ApiController{
    Future <List<Result>> indexPost() async{
      var response = await http.get(Uri.parse(ApiSettings.API_POST + "&page=0"));
      if(response != null && response.statusCode == 200) {
        if (response.body != null) {
          var autongenerater = Autogenerated.fromJson(
              jsonDecode(response.body));
          return autongenerater.result;
        }
      }
          return [];
    }
  // Future<User> login(String id, String password) async {
  //   var body = {"id": id, "ppassword": password};
  //   var response = await http.post(ApiSettings.AUTH_Login, body: body);
  //   if (response != null && response.statusCode == 200) {
  //     if (response.body != null) {
  //       var baseResponse = BaseGenericObjectResponse<User>.fromJson(
  //           jsonDecode(response.body));
  //       UserPreferences.instance.save(baseResponse.object);
  //       return baseResponse.object;
  //     }
  //   }
  //   return null;
  // }
  }
//      // print(response.body);
//       jsonDecode(response.body);
//       for (var result in autongenerater.result){
//         print("post-title ${result.postTitle} ${result.imageUrl}");
//       }
