
import 'package:kader_app/models/result.dart';

class Autogenerated {
  String recCount;
  List<Result> result;

  Autogenerated({this.recCount, this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    recCount = json['rec_count'];
    if (json['result'] != null) {
      result = List<Result>();
      json['result'].forEach((v) {
        result.add(Result.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['rec_count'] = this.recCount;
    if (this.result != null) {
      data['result'] = this.result.map((v) => v.toJson()).toList();
    }
    return data;
  }
}