import 'package:kader_app/models/autogenerated.dart';
import 'package:shared_preferences/shared_preferences.dart';

class UserPreferences {
  UserPreferences._() {
    initialize();
  }

  static UserPreferences _instance;
  SharedPreferences _pref;

  static UserPreferences get instance {
    if (_instance != null) {
      print("INITIALIZED");
      return _instance;
    } else {
      print("NOT INITIALIZED");
    }

    _instance = UserPreferences._();
    return _instance;
  }

  void initialize() async {
    _pref = await SharedPreferences.getInstance();
  }

  // final String emailKey = "email";
  // final String passwordKey = "password";
  final String isLoggedInKey = "isLoggedIn";
  final String language = "language";



  // Future<bool> login(String userEmail, String userPassword) async {
  //   String email = _pref.getString(emailKey);
  //   String password = _pref.getString(passwordKey);
  //   bool isCorrect = userEmail == email && userPassword == password;
  //   await _pref.setBool(isLoggedInKey, isCorrect);
  //   return isCorrect;
  // }

  Future logout() async {
    return await _pref.setBool(isLoggedInKey, false);
  }

  bool isLoggedIn() {
    return _pref.getBool(isLoggedInKey) ?? false;
  }

  Future changeLanguage(String code) async{
    await _pref.setString(language, code);
  }
  bool isRTL(){
    String selectedLanguage = _pref.getString(language) ?? "en";
    return selectedLanguage == "ar";
  }

  Future<bool> clear() async {
    return await _pref.clear();
  }
}
