import 'package:kader_app/models/autogenerated.dart';
import 'package:kader_app/models/user.dart';
import 'package:shared_preferences/shared_preferences.dart';

class UserPreferences {
  UserPreferences._() {
    initialize();
  }

  static UserPreferences _instance;
  SharedPreferences _pref;

  static UserPreferences get instance {
    if (_instance != null) {
      print("INITIALIZED");
      return _instance;
    } else {
      print("NOT INITIALIZED");
    }

    _instance = UserPreferences._();
    return _instance;
  }

  void initialize() async {
    print("initialize");
    _pref = await SharedPreferences.getInstance();
  }

  final String idKey = "email";
  final String passwordKey = "password";
  final String isLoggedInKey = "isLoggedIn";
  final String token = "token";
  final String language = "language";

  // Future save(User user) async{
  //   await _pref.setBool(isLoggedInKey, true);
  //   await _pref.setString(idKey, user.id);
  //   await _pref.setString(passwordKey, user.password);
  //   await _pref.setString(token, user.token);
  //
  // }

  // Future<bool> login(String userEmail, String userPassword) async {
  //   String email = _pref.getString(idKey);
  //   String password = _pref.getString(passwordKey);
  //   bool isCorrect = userEmail == email && userPassword == password;
  //   await _pref.setBool(isLoggedInKey, isCorrect);
  //   return isCorrect;
  // }

  String getToken(){
    return "Bearer" + _pref.getString(token);
  }

  Future logout() async {
    await _pref.remove(idKey);
    await _pref.remove(passwordKey);
    await _pref.remove(token);
    return await _pref.setBool(isLoggedInKey, false);
  }

  bool isLoggedIn() {
    if(_pref == null) return false;
    return _pref.getBool(isLoggedInKey) ?? false;
  }

  Future changeLanguage(String code) async{
    await _pref.setString(language, code);
  }
  bool isRTL(){
    String selectedLanguage = _pref.getString(language) ?? "en";
    return selectedLanguage == "ar";
  }

  Future<bool> clear() async {
    return await _pref.clear();
  }
}
